# Scraping Data

## Scraping Civic Coding Data

### Find all pagination links

In [13]:
import requests
import pandas as pd
import re
from bs4 import BeautifulSoup

In [30]:
base_website_to_scrape = "https://www.civic-coding.de/community-information/projekte?tx_solr%5BresultsPerPage%5D=50"

response = requests.get(base_website_to_scrape)
soup = BeautifulSoup(response.text, 'html.parser')

pagination_links = soup.find_all('a', class_='solr-ajaxified')

page_numbers = []
for link in pagination_links:
    aria_label = link.get('aria-label', '')
    if 'Gehe zu Seite:' in aria_label:
        page_num = int(aria_label.split(':')[-1].strip())
        page_numbers.append(page_num)

total_pages = max(page_numbers) if page_numbers else 1
print(f"Total pages: {total_pages}")

Total pages: 5

### Scrape all pages

In [27]:
soup_list = []

for page in range(1, total_pages + 1):
    url_to_scrape = base_website_to_scrape + "=" + str(page)
    print(f"Scraping page {page} of {total_pages}: {url_to_scrape}")
    
    response = requests.get(url_to_scrape)
    soup = BeautifulSoup(response.text, 'html.parser')
    soup_list.append(soup)

Scraping page 1 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=1
Scraping page 2 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=2
Scraping page 3 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=3
Scraping page 4 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=4
Scraping page 5 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=5
Scraping page 6 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=6
Scraping page 7 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=7
Scraping page 8 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=8
Scraping page 9 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=9
Scraping page 10 of 10: https://www.civic-coding.de/community-information/projekte?tx_solr%5Bpage%5D=10

### Get project links

In [28]:
all_link_list = []
for soup in soup_list:
    link_list = []
    project_list = soup.find_all('a', class_="position-absolute top-0 bottom-0 start-0 end-0 z-1 projectidea-link")
    
    for project in project_list:
        link = project.get('href')
        if link:  
            full_link = "https://www.civic-coding.de" + link  
            link_list.append(full_link)

    print(len(link_list))
    all_link_list.extend(link_list)

10
10
10
10
10
10
10
10
10
10

In [29]:
len(all_link_list)

100

### Alternative: Scrape with Playwright

--> See script `civic-coding-playwright-scraping.py`

## Scraping CityLab Data

In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

In [42]:
expected_data_set = pd.read_csv("Webscraping/Correlaid-Projektdatenbank/2026-01-19_Correlaid-Projekte-via-API_enriched.csv", sep=";")
expected_data_set

,Quelle,Projektname,Art,Einsatzbereich,Webseite-Link,Organisation,Status,Kurzzusammenfassung,Projekt-Abkürzung,Lizenz,Lizenz-Organisation
0,https://correlaid.org/daten-nutzen/projektdate...,Qualitätsanalyse von OpenStreetMap Daten für T...,"Datenanalyse, Explorative Analyse, Reporting, ...","Deutschland, Umweltschutz, Nachhaltigkeit, Öko...",https://correlaid.github.io/trinkbrunnen-analy...,"a tip: tap e.V., CorrelAid e.V.",In Betrieb,Wir haben Open Street Maps-Daten zu Trinkbrunn...,NaN,CC-BY 4.0,https://correlaid.org/
1,https://correlaid.org/daten-nutzen/projektdate...,Mithilfe von KI Wirkungsmessung skalieren,"KI Anwendung, Datenanalyse, Datenanwendung für...","Arbeit mit Kindern, Chancengleichheit, Inklusi...",NaN,"In safe hands e.V., CorrelAid e.V.",In Betrieb,"Wir haben ein Tool entwickelt, das die Auswert...",NaN,CC-BY 4.0,https://correlaid.org/
2,https://correlaid.org/daten-nutzen/projektdate...,Wertvolle Zeit sparen und Fehler vermeiden dur...,"Automatisierung von Prozessen, Datenanalyse, P...","Bildung, Wissenschaft, Forschung, Datenorienti...",NaN,"Science on Stage e.V., CorrelAid e.V.",In Betrieb,"Wir haben Skripte entwickelt, um die Datenvera...",NaN,CC-BY 4.0,https://correlaid.org/
3,https://correlaid.org/daten-nutzen/projektdate...,Automatisiertes Monitoring von Zielgruppenentw...,"Automatisierte Datenübermittlung, Reporting, D...","Kinder- und Jugendbildung, Bildungschancen, So...",NaN,"Chancenwerk e.V., CorrelAid e.V.",In Betrieb,Unterstützung von Chancenwerk mit automatisier...,NaN,CC-BY 4.0,https://correlaid.org/
4,https://correlaid.org/daten-nutzen/projektdate...,Automatisierte Fragebogenauswertung mit Genera...,Automatisierte Fragebogenauswertung mit Genera...,"Familienfreundlichkeit, Kinderbetreuung, Trans...",https://github.com/CorrelAid/workshop-babylots...,"Babylotse, CorrelAid e.V.",In Betrieb,Mithilfe von Large Language Models wertete Cor...,NaN,CC-BY 4.0,https://correlaid.org/
5,https://correlaid.org/daten-nutzen/projektdate...,Automatisiertes Qualitätsmanagement für ein Me...,"Automatisierte Datenübermittlung, Reporting, V...","Jugendbeteiligung, Jugendhilfe, Mentoring, Bil...",NaN,"Sindbad, CorrelAid e.V.",In Planung,Ein flexibles Dashboard: Mentoring-Feedback ei...,NaN,CC-BY 4.0,https://correlaid.org/
6,https://correlaid.org/daten-nutzen/projektdate...,Mit Daten zu transparenterer Demokratie,"Datenanalyse, Datenerhebung, Datenanwendung fü...","Demokratie, Transparenz, Demokratie-Wegweiser,...",https://civic-data.de/ein-wegweiser-fuer-die-d...,"Demokratie-Wegweiser, Civic Data Lab, CorrelAi...",In Betrieb,Entwicklung einer datenbasierten Lösung für da...,NaN,CC-BY 4.0,https://correlaid.org/
7,https://correlaid.org/daten-nutzen/projektdate...,Output Monitoring durch Entwicklung und Implem...,"Output Monitoring, Umfrage, Datenerhebung","Jugendarbeit, Jugendbeteiligung, Jugendhilfe, ...",https://civic-data.de/output-monitoring-ten-sing/,"CVJM-Gesamtverband in Deutschland e. V., Civic...",In Betrieb,"Bewältigung der Datenherausforderungen, denen ...",NaN,CC-BY 4.0,https://correlaid.org/
8,https://correlaid.org/daten-nutzen/projektdate...,Open Data aus Bürger- und Jugendbeteiligungspr...,"Datenerhebung, Datenmanagement, KI, Open Data,...","Demokratie, Jugendbeteiligung, Politische Bild...",https://civic-data.de/kommuki-open-data/,"Politik zum Anfassen e.V., Civic Data Lab, Cor...",In Betrieb,Wir unterstützten die Umsetzung eines Datenpro...,NaN,CC-BY 4.0,https://correlaid.org/
9,https://correlaid.org/daten-nutzen/projektdate...,Unterstützung des Relaunchs des Leerstandsmelders,"Datenanalyse, Datenerhebung, Digitale Plattfor...","Deutschland, Wohnen, Wohnungslosenhilfe, Sozia...","https://civic-data.de/leerstandsmelder/, https...","Leerstandsmelder; Gängeviertel e.V., Civic Dat...",In Betrieb,"Back- und Frontend, Contententwicklung, UX-Tes...",NaN,CC-BY 4.0,https://correlaid.org/
10,https://correlaid.org/daten-nutzen/projektdate...,Auswertung einer Umfrage zu KI im Ehrenamt,"Datenanalyse, Datenerhebung, Datenanwendung fü...","Arbeit mit Kindern, Antidiskriminierung, Antir...",https://digital-vereint.de/aktuelles/ki-anwend...,"Civic Data Lab, lagfa bayern, CorrelAid e.V.",In Betrieb,Auswertung und Visualisierung einer Umfrage zu...,NaN,CC-BY 4.0,https://correlaid.org/
11,https://correlaid.org/daten-nutzen/projektdate...,Data Story mit Konstanzer Klima- und Wetterdaten,"Data Story, Visualisierung, Datenmanagement, O...","Klima, Umwelt, Stadt, Konstanz, Deutschland",https://stadtdaten.konstanz.digital/stadtklima...,"Smart Green City Konstanz, CorrelAid e.V.",In Betrieb,"Wir haben eine Data Story entwickelt, die den ...",NaN,CC-BY 4.0,https://correlaid.org/
12,https://correlaid.org/daten-nutzen/projektdate...,Improving and upgrading the Silbernetz dashboard,"Reporting, Visualisierung, Wirkungsmessung, Pr...","Altersarmut, Demenz, Deutschland, Gesundheit, ...",NaN,"Silbernetz e.V., CorrelAid e.V.",In Betrieb,Eines der erfolgreichsten CorrelAid-Projekte a...,SIL,CC-BY 4.0,https://correlaid.org/
13,https://correlaid.org/daten-nutzen/projektdate...,Automatisierung von Reportings aus Evaluations...,"Automatisierung von Reportings, Datenanalyse, ...","Bildung, Kinder- und Jugendbildung, Soziale Ar...",NaN,"Coach@School, CorrelAid e.V.",In Planung,Unterstützung von coach@school mit automatisie...,NaN,CC-BY 4.0,https://correlaid.org/
14,https://correlaid.org/daten-nutzen/projektdate...,Datenbankverwaltungssystem für die Europäische...,"Datenbankverwaltungssystem, Automatisierung, O...","Europa, Zivilgesellschaft, Gemeinschaftsstiftu...",NaN,"European Community Foundation Initiative, Corr...",In Planung,"Unterstütze ECFI mit einer Datenbanklösung, di...",ECFI,CC-BY 4.0,https://correlaid.org/
15,https://correlaid.org/daten-nutzen/projektdate...,Fortschritts-Monitor,"Automatisierung, Wirkungsmessung, Prozess, Dat...","Jugendhilfe, Jugendbeteiligung, Bildung, Beruf...",NaN,"Phase BE, CorrelAid e.V.",In Betrieb,Phase BE begleitet Jugendliche beim Übergang i...,NaN,CC-BY 4.0,https://correlaid.org/
16,https://correlaid.org/daten-nutzen/projektdate...,Lebensmittelverschwendung reduzieren und Planu...,"Datenanalyse, Zeitreihenanalyse, Prozessoptimi...","Armut, Armutsbekämpfung, Soziale Arbeit, Essen...",https://osf.io/3zsn6/,"Mannheimer Platte, CorrelAid e.V.",In Betrieb,Wir analysierten die Daten des Restaurants Man...,NaN,CC-BY 4.0,https://correlaid.org/
17,https://correlaid.org/daten-nutzen/projektdate...,Analyse einer Mitgliederbefragung des Pfadfind...,"Analyse von Umfragen, Reporting, Explorative A...","Jugendarbeit, Jugendbeteiligung, Jugendhilfe, ...",NaN,"Pfadfinder*innenbund Nord, CorrelAid e.V.",In Betrieb,"Wir halfen den Pfadfindern, ihre Mitglieder be...",NaN,CC-BY 4.0,https://correlaid.org/
18,https://correlaid.org/daten-nutzen/projektdate...,Mitgliederbefragung des Turnvereins Käfertal,"Datenerhebung, Reporting, Umfrage","Sport, Soziale Arbeit",NaN,"Turnverein 1880 Käfertal, CorrelAid e.V.",In Betrieb,"Wir führten eine Mitgliederbefragung durch, um...",NaN,CC-BY 4.0,https://correlaid.org/
19,https://correlaid.org/daten-nutzen/projektdate...,tf-idf zu Babel: Text Mining zur Optimierung v...,"Datenanalyse, Datenerhebung, Datenanwendung fü...","Migration, Migrationsberatung, Integration, Ar...",NaN,"Minor Kontor, CorrelAid e.V.",In Betrieb,"Wir haben ein interaktives Tool entwickelt, um...",NaN,CC-BY 4.0,https://correlaid.org/
20,https://correlaid.org/daten-nutzen/projektdate...,Automatisierte Reportgenerierung zur Verbesser...,"Automatisierte Reportgenerierung, Datenanalyse...","Arbeit mit NGOs, Datengetriebene Prozesse, Wel...",NaN,"Weltladen Dachverband, CorrelAid e.V.",In Betrieb,Wir haben den Weltladen-Dachverband dabei unte...,NaN,CC-BY 4.0,https://correlaid.org/
21,https://correlaid.org/daten-nutzen/projektdate...,Mithilfe von Machine Learning Anomalien in Bie...,"Analyse von Sensordaten und ML, Datenanalyse, ...","Umweltschutz, Tierwohl, Landwirtschaft","https://www.youtube.com/watch?v=POqqK7Qj4cU, h...","Bee Observer BOB, CorrelAid e.V.",In Betrieb,"Wir haben BeeObserver dabei geholfen, die Bien...",BEE,CC-BY 4.0,https://correlaid.org/
22,https://correlaid.org/daten-nutzen/projektdate...,Dashboard für das Tracking von Websitezugriffs...,"Datenanalyse, Dashboard, Datenerhebung, Intern...","Datenschutz, Non-Profits, Daten nutzen, Bildun...",NaN,CorrelAid e.V.,In Betrieb,"Wir erstellten ein Dashboard, das uns half, di...",NaN,CC-BY 4.0,https://correlaid.org/
23,https://correlaid.org/daten-nutzen/projektdate...,Weiterbildungen im nachhaltigen Sektor fördern,"Datenbank, Webentwicklung, Interaktive Plattform","Nachhaltigkeit, Umweltschutz, Berufsbildung",https://www.umweltprofis.ch/assessment,"OdA Umwelt, CorrelAid e.V.",In Betrieb,Wir haben eine durchsuchbare Datenbank entwick...,NaN,CC-BY 4.0,https://correlaid.org/
24,https://correlaid.org/daten-nutzen/projektdate...,Komunat - die Wirkung von Wahlentscheidungshil...,"Wahlentscheidungshilfe, Datenanalyse, Visualis...","Demokratie, Deutschland, Kommunalwahl, Wahlent...",https://youtu.be/JJoEJGc1eNc?t=2745,"VOTO, CorrelAid e.V.",In Betrieb,Für die Kommunalwahl 2019 in Stuttgart haben w...,NaN,CC-BY 4.0,https://correlaid.org/
25,https://correlaid.org/daten-nutzen/projektdate...,Wer ist interessiert an einem guten Leben im l...,"Datenerhebung, Umfrage, Verwaltung","Arbeit mit Kindern, Alter, Demenz, Gesundheit,...",https://www.berliner-zeitung.de/mensch-metropo...,"Denk-mal-Kultur e.V., CorrelAid e.V.",In Betrieb,Wir haben Denk-mal-Kultur e.V. dabei unterstüt...,NaN,CC-BY 4.0,https://correlaid.org/
26,https://correlaid.org/daten-nutzen/projektdate...,Interaktives Dashboard zur besseren Darstellun...,"Interaktive Karte, Automatisierung, Datenerheb...","Entschuldung, Schulden, Entwicklung, Zivilgese...","https://github.com/CorrelAid/erlassjahr, https...","Erlassjahr e.V., CorrelAid e.V.",In Betrieb,"Wir halfen dem erlassjahr-Team, Zeit und Mühe ...",NaN,CC-BY 4.0,https://correlaid.org/
27,https://correlaid.org/daten-nutzen/projektdate...,Anschauliche Aufbereitung von Umfragen zur Tei...,"Datenanalyse, Datenerhebung, Umfrage, Visualis...","Europa, Bildung, Jugend, Teilhabe, Internation...",NaN,"European Youth Parliament, CorrelAid e.V.",In Betrieb,Wir analysierten Umfragedaten von fünf Veranst...,NaN,CC-BY 4.0,https://correlaid.org/
28,https://correlaid.org/daten-nutzen/projektdate...,Netzwerkdynamiken in Citizen Science - Nutzer*...,"Datenanalyse, Netzwerkdynamiken, Citizen Scien...","Umwelt, Citizen Science, Datenanalyse",https://github.com/correlaid-paris/citizen_sci...,CorrelAid e.V.,In Betrieb,Wir halfen bei der Analyse von Daten der Citiz...,NaN,CC-BY 4.0,https://correlaid.org/
29,https://correlaid.org/daten-nutzen/projektdate...,Datenvisualisierungen für mehr Aufmerksamkeit ...,"Datenanalyse, Datenvisualisierung, Advocacy","Menschenrechte, Migration, Mittelmeer",https://cms.correlaid.org/assets/0620a79e-e97d...,"Mare Liberum, CorrelAid e.V.",In Betrieb,"Wir haben Mare Liberum dabei geholfen, ihre Da...",NaN,CC-BY 4.0,https://correlaid.org/
30,https://correlaid.org/daten-nutzen/projektdate...,Diversität erforschen - Visualisierung der Afr...,"Datenanalyse, Datenerhebung, Datenvisualisieru...","Antidiskriminierung, Antirassismus, Chancengle...",https://afrozensus.de,"Citizens for Europe, CorrelAid e.V.",In Betrieb,"Wir haben ein R-Paket entwickelt, das Forscher...",NaN,CC-BY 4.0,https://correlaid.org/
31,https://correlaid.org/daten-nutzen/projektdate...,Erstellung eines interaktiven Survey-Reports f...,"Datenanalyse, Datenerhebung, Datenvisualisieru...","Ghana, Afrika, Internationale Zusammenarbeit, ...",https://github.com/CorrelAid/hacklab-foundatio...,"Hacklab Foundation, CorrelAid e.V.",In Betrieb,"Wir haben Umfragedaten analysiert, um Einblick...",NaN,CC-BY 4.0,https://correlaid.org/
32,https://correlaid.org/daten-nutzen/projektdate...,Ein Dashboard zur Steigerung der Motivation vo...,"Dashboard, Datenanalyse, Webentwicklung","Bildung, Chancengleichheit, Ehrenamt, Gerechti...",https://github.com/CorrelAid/naklar.io,CorrelAid e.V.,In Betrieb,Wir halfen bei der Erstellung eines Dashboards...,NaN,CC-BY 4.0,https://correlaid.org/
33,https://correlaid.org/daten-nutzen/projektdate...,R Wrapper für die KoboToolbox API,"Datenerhebung, Open-Source-Tool, R-Wrapper, AP...","Daten nutzen, Bildung, Forschung, Humanitäre H...","https://github.com/CorrelAid/kbtbr, https://co...",CorrelAid e.V.,In Betrieb,Mit dem R-Paket CorrelAid für KoboToolbox habe...,NaN,CC-BY 4.0,https://correlaid.org/
34,https://correlaid.org/daten-nutzen/projektdate...,Zeitersparnisse und verbesserte Wirkungskommun...,"Automatisierung, Visualisierung","Altersarmut, Demenz, Gesundheit, Inklusion, Me...",NaN,"Silbernetz e.V., CorrelAid e.V.",In Betrieb,"Wir haben ein interaktives Tool entwickelt, da...",NaN,CC-BY 4.0,https://correlaid.org/
35,https://correlaid.org/daten-nutzen/projektdate...,Alleinerziehend und arbeitslos: Analyse von Da...,"Analyse von Sensordaten und ML, Datenanalyse, ...","Armut, Arbeit mit Kindern, Beratung, Chancengl...",https://www.caritas.de/neue-caritas/heftarchiv...,"Deutscher Caritasverband e.V., Referat Soziale...",In Betrieb,Wir haben die Daten von 37 000 Kunden analysie...,NaN,CC-BY 4.0,https://correlaid.org/
36,https://correlaid.org/daten-nutzen/projektdate...,Python-Package für die GENESIS Datenbank,"Datenanalyse, Datenerhebung, Datenanwendung fü...","Deutschland, Statistik, Datenbanken, Open Data",https://github.com/CorrelAid/pystatis,CorrelAid e.V.,In Betrieb,Das CorrelAid Team entwickelte ein Python-Pack...,NaN,CC-BY 4.0,https://correlaid.org/
37,https://correlaid.org/daten-nutzen/projektdate...,R Wrapper for the Genesis API,"Datenanalyse, Datenerhebung, Datenanwendung fü...","Datenschutz, Offene Daten, Soziale Arbeit, Woh...","https://github.com/CorrelAid/restatis, https:/...",CorrelAid e.V.,In Betrieb,"Das CorrelAid Team entwickelte ein R-Package, ...",NaN,CC-BY 4.0,https://correlaid.org/
38,https://correlaid.org/daten-nutzen/projektdate...,Entwicklung eines interaktiven Fragebogens zur...,"Interaktive Web App, Visualisierung, Webentwic...","Kinderschutz, Sport, Deutschland, Österreich, ...",https://laureus.shinyapps.io/Safeinsport-selfa...,"Laureus Sport For Good Germany, CorrelAid e.V.",In Betrieb,"Wir haben eine interaktive Web-App entwickelt,...",NaN,CC-BY 4.0,https://correlaid.org/
39,https://correlaid.org/daten-nutzen/projektdate...,Wo sollen neue Fahrradparkplätze in Paris ents...,"Interaktive Karte, Datenanalyse, Offene Daten","Frankreich, Paris, Verwaltung, Stadtplanung, F...","https://github.com/CorrelAid/paris-bikes/, htt...","City of Paris , CorrelAid e.V.",In Betrieb,Wir haben die Stadt Paris bei der Erstellung e...,NaN,CC-BY 4.0,https://correlaid.org/
40,https://correlaid.org/daten-nutzen/projektdate...,Aufbau eines Systems zur Bewertung der Bodenqu...,"Analyse von Sensordaten und ML, Computer Visio...","Umwelt, Landwirtschaft, Nachhaltigkeit",NaN,CorrelAid e.V.,unclear,Wir haben maschinelles Lernen und Computer Vis...,NaN,CC-BY 4.0,https://correlaid.org/
41,https://correlaid.org/daten-nutzen/projektdate...,ETL Pipeline von Limesurvey zu einer Datenbank,"Datenanalyse, Datenerhebung, Datenanwendung fü...","Datenmanagement, Umfrage, Non-Profit, Data4Good",NaN,CorrelAid e.V.,In Betrieb,"Wir haben dazu beigetragen, die Datenextraktio...",NaN,CC-BY 4.0,https://correlaid.org/
42,https://correlaid.org/daten-nutzen/projektdate...,Datenfluss von R zu Metabase zu Google Docs: e...,"Automatisierung, Webentwicklung, Umfrage, Prozess","Datenpipelines, Google Workspace, Metabase, R,...",https://github.com/CorrelAid/metabase-to-googl...,CorrelAid e.V.,In Betrieb,Wir haben erfolgreich zwei Komponenten zur Aut...,NaN,CC-BY 4.0,https://correlaid.org/

In [3]:
url = 'https://citylab-berlin.org/de/projects/'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

In [4]:
def assign_project_status(chunk):
    if chunk == 0:
        return "In Planung"
    else:
        return "In Betrieb"

def collect_project_categories(project_data):
    category_texts = []
    categories = project_data.find('div', class_="wpgb-block-2").find_all("a")
    for category in categories:
        category_text = category.text
        category_texts.append(category_text)

    list_as_string = ', '.join(category_texts)
    
    return list_as_string

In [5]:
project_chunks = soup.find_all('div', class_='wpgb-masonry')
projects_df=pd.DataFrame()

for chunk in range(len(project_chunks)):
    for project in project_chunks[chunk].find_all('article'): 
        quelle = project.find('a', class_="wpgb-card-layer-link").get('href')
        title = project.find("h3", class_="wpgb-block-3 wpgb-idle-scheme-1").text
        project_summary = project.find(class_="wpgb-block-6 wpgb-idle-scheme-2").text

        project_categories = collect_project_categories(project)

        # Collect data in a DataFrame
        data = {
            "Quelle": quelle,
            "Projektname": title,
            "Einsatzbereich": f"{project_categories}",
            "Webseite-Link": quelle,
            "Organisation": "CityLAB Berlin",
            "Status": assign_project_status(chunk),
            "Kurzzusammenfassung": project_summary,
            "Lizenz": "?", # TODO: Discuss with CDL Team
            "Lizenz-Organisation": "https://citylab-berlin.org"
        }
        df = pd.DataFrame(data, index=[0])
        projects_df = pd.concat([projects_df, df], ignore_index=True)

In [10]:
projects_df["Index"] = projects_df.index
projects_df

,index,Quelle,Projektname,Einsatzbereich,Webseite-Link,Organisation,Status,Kurzzusammenfassung,Lizenz,Lizenz-Organisation,Index
0,0,https://citylab-berlin.org/de/projects/baergpt/,BärGPT,"DE, Digitale Zusammenarbeit, Neue Technologien",https://citylab-berlin.org/de/projects/baergpt/,CityLAB Berlin,In Planung,Der KI-Assistent für die Berliner Landesverwal...,?,https://citylab-berlin.org,0
1,1,https://citylab-berlin.org/de/projects/fairgnu...,Fairgnügen,"DE, Digitale Zusammenarbeit, Innovative Verwal...",https://citylab-berlin.org/de/projects/fairgnu...,CityLAB Berlin,In Planung,Unsere neue Webseite hilft bei der Suche nach ...,?,https://citylab-berlin.org,1
2,2,https://citylab-berlin.org/de/projects/parla/,Parla,"DE, Digitale Zusammenarbeit, Innovative Verwal...",https://citylab-berlin.org/de/projects/parla/,CityLAB Berlin,In Planung,Das neue KI-Tool Parla macht Schriftliche Anfr...,?,https://citylab-berlin.org,2
3,3,https://citylab-berlin.org/de/projects/kiezlabor/,Kiezlabor,"DE, Digitale Zusammenarbeit, Innovative Verwal...",https://citylab-berlin.org/de/projects/kiezlabor/,CityLAB Berlin,In Planung,Das Kiezlabor bringt den prototypischen Ansatz...,?,https://citylab-berlin.org,3
4,4,https://citylab-berlin.org/de/projects/data-hu...,Data Hub Berlin,"DE, Innovative Verwaltung, Offene Daten, Open ...",https://citylab-berlin.org/de/projects/data-hu...,CityLAB Berlin,In Planung,Die zentrale Plattform für ein bessere Wertsch...,?,https://citylab-berlin.org,4
5,5,https://citylab-berlin.org/de/projects/partizi...,Partizipation Digital,"DE, Digitale Zusammenarbeit, Innovative Verwal...",https://citylab-berlin.org/de/projects/partizi...,CityLAB Berlin,In Planung,Eine prototypische Lösung soll den Ankunftspro...,?,https://citylab-berlin.org,5
6,6,https://citylab-berlin.org/de/projects/govtech...,GovTech TestLAB,"DE, Digitale Zusammenarbeit, Innovative Verwal...",https://citylab-berlin.org/de/projects/govtech...,CityLAB Berlin,In Planung,"Wir schaffen einen Raum, in dem Lösungen auspr...",?,https://citylab-berlin.org,6
7,7,https://citylab-berlin.org/de/projects/stadtla...,Stadtlabor2Go,"DE, Digitale Zusammenarbeit, Innovative Verwal...",https://citylab-berlin.org/de/projects/stadtla...,CityLAB Berlin,In Planung,"Stadtlabor2Go zeigt, wie Städte Digitalisierun...",?,https://citylab-berlin.org,7
8,8,https://citylab-berlin.org/de/projects/giess-d...,Gieß den Kiez,"DE, Energie und Nachhaltigkeit, Offene Daten, ...",https://citylab-berlin.org/de/projects/giess-d...,CityLAB Berlin,In Planung,Gieß den Kiez ist eine Plattform zur Koordinie...,?,https://citylab-berlin.org,8
9,9,https://citylab-berlin.org/de/projects/klimada...,KlimaDashboard Xhain,"DE, Digitale Zusammenarbeit, Energie und Nachh...",https://citylab-berlin.org/de/projects/klimada...,CityLAB Berlin,In Planung,Mit dem Klimadashboard werden Klimadaten trans...,?,https://citylab-berlin.org,9
10,10,https://citylab-berlin.org/de/projects/hilf-mi...,Hilf-Mir.Berlin,"DE, Innovative Verwaltung",https://citylab-berlin.org/de/projects/hilf-mi...,CityLAB Berlin,In Planung,Hilf-Mir.Berlin fasst das Angebot von über 200...,?,https://citylab-berlin.org,10
11,11,https://citylab-berlin.org/de/projects/talking...,Talking Treebot,"DE, Energie und Nachhaltigkeit, Offene Daten, ...",https://citylab-berlin.org/de/projects/talking...,CityLAB Berlin,In Planung,Der Talking Treebot gibt den Berliner Stadtbäu...,?,https://citylab-berlin.org,11
12,12,https://citylab-berlin.org/de/projects/buerger...,Bürgeramt der Zukunft,"DE, Innovative Verwaltung",https://citylab-berlin.org/de/projects/buerger...,CityLAB Berlin,In Planung,Das Ziel des Projekts Bürgeramt der Zukunft is...,?,https://citylab-berlin.org,12
13,13,https://citylab-berlin.org/de/projects/citylab...,CityLAB Roadshow,"DE, Innovative Verwaltung",https://citylab-berlin.org/de/projects/citylab...,CityLAB Berlin,In Planung,Das CityLAB Berlin kommt zum Hausbesuch.,?,https://citylab-berlin.org,13
14,14,https://citylab-berlin.org/de/projects/berline...,Berliner EnergieCheckpoint,"DE, Offene Daten, offene Städte",https://citylab-berlin.org/de/projects/berline...,CityLAB Berlin,In Planung,Der EnergieCheckpoint zeigt Daten zum Energiev...,?,https://citylab-berlin.org,14
15,15,https://citylab-berlin.org/de/projects/smart_c...,Gemeinsam Digital: Berlin,"DE, Smart Cities für alle",https://citylab-berlin.org/de/projects/smart_c...,CityLAB Berlin,In Planung,Wir unterstützen die Maßnahmen der Smart City ...,?,https://citylab-berlin.org,15
16,16,https://citylab-berlin.org/de/projects/ki-zum-...,KI zum Anfassen,"DE, Prototyping",https://citylab-berlin.org/de/projects/ki-zum-...,CityLAB Berlin,In Planung,Hier stellen wir euch vier unserer aktuellen K...,?,https://citylab-berlin.org,16
17,17,https://citylab-berlin.org/de/projects/labcamp/,LabCamp,"DE, Digitale Zusammenarbeit, Digitale Zusammen...",https://citylab-berlin.org/de/projects/labcamp/,CityLAB Berlin,In Planung,Das LabCamp ist ein Vernetzungstreffen öffentl...,?,https://citylab-berlin.org,17
18,18,https://citylab-berlin.org/de/projects/summers...,Summer School,"DE, Smart Cities für alle",https://citylab-berlin.org/de/projects/summers...,CityLAB Berlin,In Planung,Summer School zu jährlich wechselnden Themen.,?,https://citylab-berlin.org,18
19,19,https://citylab-berlin.org/de/projects/berline...,Berliner Weihnachtsmarkt-Finder,"DE, Offene Daten, offene Städte, Open Source",https://citylab-berlin.org/de/projects/berline...,CityLAB Berlin,In Planung,"Glühwein, Glögg, Glückseligkeit – Berliner Wei...",?,https://citylab-berlin.org,19
20,20,https://citylab-berlin.org/de/projects/digital...,Digitalwerkstatt Verwaltung,"DE, Innovative Verwaltung",https://citylab-berlin.org/de/projects/digital...,CityLAB Berlin,In Planung,In der Digitalwerkstatt werden gemeinsam mit B...,?,https://citylab-berlin.org,20
21,21,https://citylab-berlin.org/de/projects/werksta...,Werkstatt im CityLAB,"DE, Smart Cities für alle",https://citylab-berlin.org/de/projects/werksta...,CityLAB Berlin,In Planung,Die Werkstatt ist Raum für Experiment und Meth...,?,https://citylab-berlin.org,21
22,22,https://citylab-berlin.org/de/projects/hacking...,Hacking Box goes CityLAB Berlin,"DE, Digitale Zusammenarbeit",https://citylab-berlin.org/de/projects/hacking...,CityLAB Berlin,In Planung,"Hardwareboxen für Schulprojekte, Workshops, Se...",?,https://citylab-berlin.org,22
23,23,https://citylab-berlin.org/de/projects/digital...,Digital Vereint – mit digitalen Tools das Berl...,"DE, Smart Cities für alle",https://citylab-berlin.org/de/projects/digital...,CityLAB Berlin,In Betrieb,Digital Vereint ist eine Plattform zur Unterst...,?,https://citylab-berlin.org,23
24,24,https://citylab-berlin.org/de/projects/qtrees/,Quantified Trees (Qtrees): Intelligente Bewäss...,"DE, Energie und Nachhaltigkeit",https://citylab-berlin.org/de/projects/qtrees/,CityLAB Berlin,In Betrieb,Im Forschungsprojekt QTrees werden von Trocken...,?,https://citylab-berlin.org,24
25,25,https://citylab-berlin.org/de/projects/afs-das...,Verwaltungsdashboard,"DE, Innovative Verwaltung",https://citylab-berlin.org/de/projects/afs-das...,CityLAB Berlin,In Betrieb,Im Rahmen von Design Sprints unterstützten wir...,?,https://citylab-berlin.org,25
26,26,https://citylab-berlin.org/de/projects/stadtpuls/,Stadtpuls – Deine Sensoren erklären Berlin,"DE, Offene Daten, offene Städte, Smart Cities ...",https://citylab-berlin.org/de/projects/stadtpuls/,CityLAB Berlin,In Betrieb,Stadtpuls ist eine offene IoT-Datenplattform f...,?,https://citylab-berlin.org,26
27,27,https://citylab-berlin.org/de/projects/pixelwelt/,Pixelwelt,"DE, Digitale Zusammenarbeit",https://citylab-berlin.org/de/projects/pixelwelt/,CityLAB Berlin,In Betrieb,Die Pixelwelt ist ein digitales 2D-Modell des ...,?,https://citylab-berlin.org,27
28,28,https://citylab-berlin.org/de/projects/prototy...,Prototypenwerkstatt – Am Beispiel der Senioren...,"DE, Innovative Verwaltung",https://citylab-berlin.org/de/projects/prototy...,CityLAB Berlin,In Betrieb,Prototypisch digitale Projekte zur Ablösung vo...,?,https://citylab-berlin.org,28
29,29,https://citylab-berlin.org/de/projects/prozess...,Prozessanalyse Radinfrastruktur (PARI),"DE, Energie und Nachhaltigkeit, Offene Daten, ...",https://citylab-berlin.org/de/projects/prozess...,CityLAB Berlin,In Betrieb,Analyse von Prozessen und Verfahren der Berlin...,?,https://citylab-berlin.org,29
30,30,https://citylab-berlin.org/de/projects/digital...,FixMyBerlin – Digitale Tools für Radwegeplanung,"DE, Innovative Verwaltung",https://citylab-berlin.org/de/projects/digital...,CityLAB Berlin,In Betrieb,Das Projekt begleitet die Berliner Verwaltung ...,?,https://citylab-berlin.org,30
31,31,https://citylab-berlin.org/de/projects/schatten/,Berliner Erfrischungskarte,"DE, Offene Daten, offene Städte",https://citylab-berlin.org/de/projects/schatten/,CityLAB Berlin,In Betrieb,Open Data-basierte Kartenvisualisierung.,?,https://citylab-berlin.org,31
32,32,https://citylab-berlin.org/de/projects/clair/,Clair Berlin,"DE, Energie und Nachhaltigkeit",https://citylab-berlin.org/de/projects/clair/,CityLAB Berlin,In Betrieb,Initiative zur Messung von Luftqualität in öff...,?,https://citylab-berlin.org,32
33,33,https://citylab-berlin.org/de/projects/aiforbe...,AI for Berlin,"DE, Offene Daten, offene Städte, Smart Cities ...",https://citylab-berlin.org/de/projects/aiforbe...,CityLAB Berlin,In Betrieb,Workshopreihe zum Nutzen von KI im Kontext urb...,?,https://citylab-berlin.org,33
34,34,https://citylab-berlin.org/de/projects/bikesha...,Shared Mobility Flows,"DE, Energie und Nachhaltigkeit, Offene Daten, ...",https://citylab-berlin.org/de/projects/bikesha...,CityLAB Berlin,In Betrieb,Das Projekt analysiert und visualisiert Leihfa...,?,https://citylab-berlin.org,34
35,35,https://citylab-berlin.org/de/projects/traffic...,Open Traffic Count,"DE, Energie und Nachhaltigkeit, Offene Daten, ...",https://citylab-berlin.org/de/projects/traffic...,CityLAB Berlin,In Betrieb,Das Projekt evaluiert Anwendungen zu Verkehrsz...,?,https://citylab-berlin.org,35
36,36,https://citylab-berlin.org/de/projects/distric...,Bezirksregionen digital,"DE, Innovative Verwaltung, Offene Daten, offen...",https://citylab-berlin.org/de/projects/distric...,CityLAB Berlin,In Betrieb,Projekt zur Vereinheitlichung und Zugänglichke...,?,https://citylab-berlin.org,36
37,37,https://citylab-berlin.org/de/projects/stadtvi...,Algorithmische Stadtvisionen,"DE, Neue Technologien",https://citylab-berlin.org/de/projects/stadtvi...,CityLAB Berlin,In Betrieb,Im Projekt wird KI und maschinelles Lernens fü...,?,https://citylab-berlin.org,37
38,38,https://citylab-berlin.org/de/projects/startup...,Berlin Urban Tech-Datenbank,"DE, Offene Daten, offene Städte",https://citylab-berlin.org/de/projects/startup...,CityLAB Berlin,In Betrieb,Vernetzung von Start-Ups im Urban Tech-Bereich...,?,https://citylab-berlin.org,38
39,39,https://citylab-berlin.org/de/projects/prototype/,Prototype Your Future City!,"DE, Smart Cities für alle",https://citylab-berlin.org/de/projects/prototype/,CityLAB Berlin,In Betrieb,Studierende der HTW Berlin arbeiten an ihren g...,?,https://citylab-berlin.org,39

In [ ]:

laufend_chunk = first_chunks[0].find_all('article')
abgeschlossen_chunk = first_chunks[1].find_all('article')

In [ ]:
laufend_dict = {}

for tile in laufend_chunk: 
    sub_domain_link = tile.find('a', class_="wpgb-card-layer-link").get('href')
    h3 = tile.find('h3', class_="wpgb-block-3 wpgb-idle-scheme-1")
    if h3:
        textlink = h3.find('a')
        if textlink:
            title = textlink.text
    
    category_texts = []
    cat = tile.find('div', class_="wpgb-block-2")
    if cat: 
        categories = cat.find_all('a')
        if categories:
            for category in categories:
                category_text = category.text
                category_texts.append(category_text)
    
    project_summary = tile.find(class_="wpgb-block-6 wpgb-idle-scheme-2").text
    
    laufend_dict[title] = {
        "Quelle" : sub_domain_link,
        "Einsatzbereich" : category_texts,
        "Kurzzusammenfassung" : project_summary
    } 

for key in list(laufend_dict.keys()):
    split_string = re.split(r'[\\]', key)
    if split_string:  # Check if the split string has elements
        new_key = split_string[0].strip()
    laufend_dict[new_key] = laufend_dict.pop(key)

laufend_dict

{'BärGPT': {'sub-link': 'https://citylab-berlin.org/de/projects/baergpt/',
  'Einsatzbereich': ['Digitale Zusammenarbeit', 'Neue Technologien'],
  'Kurzzusammenfassung': 'Der KI-Assistent für die Berliner Landesverwaltung.'},
 'Fairgnügen': {'sub-link': 'https://citylab-berlin.org/de/projects/fairgnuegen/',
  'Einsatzbereich': ['Digitale Zusammenarbeit',
   'Innovative Verwaltung',
   'Prototyping'],
  'Kurzzusammenfassung': 'Unsere neue Webseite hilft bei der Suche nach über 400 kostenlosen und ermäßigten Angeboten.'},
 'Parla': {'sub-link': 'https://citylab-berlin.org/de/projects/parla/',
  'Einsatzbereich': ['Digitale Zusammenarbeit',
   'Innovative Verwaltung',
   'Neue Technologien'],
  'Kurzzusammenfassung': 'Das neue KI-Tool Parla macht Schriftliche Anfragen durchsuchbar. '},
 'Kiezlabor': {'sub-link': 'https://citylab-berlin.org/de/projects/kiezlabor/',
  'Einsatzbereich': ['Digitale Zusammenarbeit',
   'Innovative Verwaltung',
   'Offene Daten, offene Städte',
   'Smart Cities für alle'],
  'Kurzzusammenfassung': 'Das Kiezlabor bringt den prototypischen Ansatz des CityLAB Berlin in die Kieze.'},
 'Data Hub Berlin': {'sub-link': 'https://citylab-berlin.org/de/projects/data-hub-berlin/',
  'Einsatzbereich': ['Innovative Verwaltung', 'Offene Daten', 'Open Source'],
  'Kurzzusammenfassung': 'Die zentrale Plattform für ein bessere Wertschöpfung der Berliner Datenschätze. '},
 'Partizipation Digital': {'sub-link': 'https://citylab-berlin.org/de/projects/partizipation-digital/',
  'Einsatzbereich': ['Digitale Zusammenarbeit', 'Innovative Verwaltung'],
  'Kurzzusammenfassung': 'Eine prototypische Lösung soll den Ankunftsprozess unterstützen und verbessern.'},
 'GovTech TestLAB': {'sub-link': 'https://citylab-berlin.org/de/projects/govtech-testlab/',
  'Einsatzbereich': ['Digitale Zusammenarbeit',
   'Innovative Verwaltung',
   'Open Source'],
  'Kurzzusammenfassung': 'Wir schaffen einen Raum, in dem Lösungen ausprobiert und bewertet werden können.'},
 'Stadtlabor2Go': {'sub-link': 'https://citylab-berlin.org/de/projects/stadtlabor2go/',
  'Einsatzbereich': ['Digitale Zusammenarbeit',
   'Innovative Verwaltung',
   'Offene Daten, offene Städte'],
  'Kurzzusammenfassung': 'Stadtlabor2Go zeigt, wie Städte Digitalisierung gemeinsam voranbringen können.'},
 'Gieß den Kiez': {'sub-link': 'https://citylab-berlin.org/de/projects/giess-den-kiez/',
  'Einsatzbereich': ['Energie und Nachhaltigkeit',
   'Offene Daten, offene Städte'],
  'Kurzzusammenfassung': 'Gieß den Kiez ist eine Plattform zur Koordinierung der Bewässerung der Berliner Bäume.'},
 'KlimaDashboard Xhain': {'sub-link': 'https://citylab-berlin.org/de/projects/klimadashboard-xhain/',
  'Einsatzbereich': ['Digitale Zusammenarbeit',
   'Energie und Nachhaltigkeit',
   'Innovative Verwaltung'],
  'Kurzzusammenfassung': 'Mit dem Klimadashboard werden Klimadaten transparen.'},
 'Hilf-Mir.Berlin': {'sub-link': 'https://citylab-berlin.org/de/projects/hilf-mir-berlin/',
  'Einsatzbereich': ['Innovative Verwaltung'],
  'Kurzzusammenfassung': 'Hilf-Mir.Berlin fasst das Angebot von über 200 Beratungsstellen erstmals übersichtlich zusammen. '},
 'Talking Treebot': {'sub-link': 'https://citylab-berlin.org/de/projects/talking-treebot/',
  'Einsatzbereich': ['Energie und Nachhaltigkeit',
   'Offene Daten, offene Städte'],
  'Kurzzusammenfassung': 'Der Talking Treebot gibt den Berliner Stadtbäumen mit Hilfe von Künstlicher Intelligenz eine Stimme.'},
 'Bürgeramt der Zukunft': {'sub-link': 'https://citylab-berlin.org/de/projects/buergeramt-der-zukunft-tagebuchstudie/',
  'Einsatzbereich': ['Innovative Verwaltung'],
  'Kurzzusammenfassung': 'Das Ziel des Projekts Bürgeramt der Zukunft ist es, ein tieferes Verständnis für die Arbeit und die Abläufe in der Verwaltung zu erhalten und diese hinsichtlich ihrer Nutzer:innenorientierung zu verbessern.'},
 'CityLAB Roadshow': {'sub-link': 'https://citylab-berlin.org/de/projects/citylab-roadshow/',
  'Einsatzbereich': ['Innovative Verwaltung'],
  'Kurzzusammenfassung': 'Das CityLAB Berlin kommt zum Hausbesuch.'},
 'Berliner EnergieCheckpoint': {'sub-link': 'https://citylab-berlin.org/de/projects/berliner-energiecheckpoint/',
  'Einsatzbereich': ['Offene Daten, offene Städte'],
  'Kurzzusammenfassung': 'Der\xa0EnergieCheckpoint\xa0zeigt Daten zum Energieverbrauch öffentlicher Gebäude.'},
 'Gemeinsam Digital: Berlin': {'sub-link': 'https://citylab-berlin.org/de/projects/smart_city/',
  'Einsatzbereich': ['Smart Cities für alle'],
  'Kurzzusammenfassung': 'Wir unterstützen die Maßnahmen der Smart City Strategie “Gemeinsam Digital: Berlin”.'},
 'KI zum Anfassen': {'sub-link': 'https://citylab-berlin.org/de/projects/ki-zum-anfassen-unsere-interaktiven-exponate/',
  'Einsatzbereich': ['Prototyping'],
  'Kurzzusammenfassung': 'Hier stellen wir euch vier unserer aktuellen KI-Experimente vor, die in unserem Prototyping-Team entstanden sind.'},
 'LabCamp': {'sub-link': 'https://citylab-berlin.org/de/projects/labcamp/',
  'Einsatzbereich': ['Digitale Zusammenarbeit',
   'Innovative Verwaltung',
   'Offene Daten, offene Städte',
   'Digitale Zusammenarbeit'],
  'Kurzzusammenfassung': 'Das LabCamp ist ein Vernetzungstreffen öffentlicher Innovationslabore.'},
 'Summer School': {'sub-link': 'https://citylab-berlin.org/de/projects/summerschool/',
  'Einsatzbereich': ['Smart Cities für alle'],
  'Kurzzusammenfassung': 'Summer School zu jährlich wechselnden Themen.'},
 'Berliner Weihnachtsmarkt-Finder': {'sub-link': 'https://citylab-berlin.org/de/projects/berliner-weihnachtsmarkt-finder/',
  'Einsatzbereich': ['Offene Daten', 'offene Städte', 'Open Source'],
  'Kurzzusammenfassung': 'Glühwein, Glögg, Glückseligkeit – Berliner Weihnachtsmärkte auf einen Blick!'},
 'Digitalwerkstatt Verwaltung': {'sub-link': 'https://citylab-berlin.org/de/projects/digitalwerkstatt/',
  'Einsatzbereich': ['Innovative Verwaltung'],
  'Kurzzusammenfassung': 'In der Digitalwerkstatt werden gemeinsam mit Bürger:innen Verwaltungsformulare verbessert.'},
 'Werkstatt im CityLAB': {'sub-link': 'https://citylab-berlin.org/de/projects/werkstatt-im-citylab/',
  'Einsatzbereich': ['Smart Cities für alle'],
  'Kurzzusammenfassung': 'Die Werkstatt ist Raum für Experiment und Methoden der Elektrotechnik und Informatik.'},
 'Hacking Box goes CityLAB Berlin': {'sub-link': 'https://citylab-berlin.org/de/projects/hacking-box-goes-citylab/',
  'Einsatzbereich': ['Digitale Zusammenarbeit'],
  'Kurzzusammenfassung': 'Hardwareboxen für Schulprojekte, Workshops, Seminare, Hackathons & Co.'}}

In [ ]:
abgeschlossen_dict = {}

for tile in abgeschlossen_chunk: 
    sub_domain_link = tile.find('a', class_="wpgb-card-layer-link").get('href')
    h3 = tile.find('h3', class_="wpgb-block-3 wpgb-idle-scheme-1")
    if h3:
        textlink = h3.find('a')
        if textlink:
            title = textlink.text

    category_texts = []
    cat = tile.find('div', class_="wpgb-block-2")
    if cat: 
        categories = cat.find_all('a')
        if categories:
            for category in categories:
                category_text = category.text
                category_texts.append(category_text)

    abgeschlossen_dict[title] = {
        "sub-link" : sub_domain_link,
        "Einsatzbereich" : category_texts
    } 

for key in list(abgeschlossen_dict.keys()):
    split_string = re.split(r'[\–\-\:]', key)
    if split_string:  # Check if the split string has elements
        new_key = split_string[0].strip()
    abgeschlossen_dict[new_key] = abgeschlossen_dict.pop(key)

abgeschlossen_dict

{'Digital Vereint': {'sub-link': 'https://citylab-berlin.org/de/projects/digitalvereint/',
  'Einsatzbereich': ['Smart Cities für alle']},
 'Quantified Trees (Qtrees)': {'sub-link': 'https://citylab-berlin.org/de/projects/qtrees/',
  'Einsatzbereich': ['Energie und Nachhaltigkeit']},
 'Verwaltungsdashboard': {'sub-link': 'https://citylab-berlin.org/de/projects/afs-dashboard/',
  'Einsatzbereich': ['Innovative Verwaltung']},
 'Stadtpuls': {'sub-link': 'https://citylab-berlin.org/de/projects/stadtpuls/',
  'Einsatzbereich': ['Offene Daten, offene Städte', 'Smart Cities für alle']},
 'Pixelwelt': {'sub-link': 'https://citylab-berlin.org/de/projects/pixelwelt/',
  'Einsatzbereich': ['Digitale Zusammenarbeit']},
 'Prototypenwerkstatt': {'sub-link': 'https://citylab-berlin.org/de/projects/prototypenwerkstatt/',
  'Einsatzbereich': ['Innovative Verwaltung']},
 'Prozessanalyse Radinfrastruktur (PARI)': {'sub-link': 'https://citylab-berlin.org/de/projects/prozessanalyse-radinfrastruktur-pari/',
  'Einsatzbereich': ['Energie und Nachhaltigkeit',
   'Offene Daten, offene Städte']},
 'FixMyBerlin': {'sub-link': 'https://citylab-berlin.org/de/projects/digitale-tools-fuer-radwegeplanung/',
  'Einsatzbereich': ['Innovative Verwaltung']},
 'Berliner Erfrischungskarte': {'sub-link': 'https://citylab-berlin.org/de/projects/schatten/',
  'Einsatzbereich': ['Offene Daten, offene Städte']},
 'Clair Berlin': {'sub-link': 'https://citylab-berlin.org/de/projects/clair/',
  'Einsatzbereich': ['Energie und Nachhaltigkeit']},
 'AI for Berlin': {'sub-link': 'https://citylab-berlin.org/de/projects/aiforberlin/',
  'Einsatzbereich': ['Offene Daten, offene Städte', 'Smart Cities für alle']},
 'Shared Mobility Flows': {'sub-link': 'https://citylab-berlin.org/de/projects/bikesharing/',
  'Einsatzbereich': ['Energie und Nachhaltigkeit',
   'Offene Daten, offene Städte']},
 'Open Traffic Count': {'sub-link': 'https://citylab-berlin.org/de/projects/trafficcount/',
  'Einsatzbereich': ['Energie und Nachhaltigkeit',
   'Offene Daten, offene Städte']},
 'Bezirksregionen digital': {'sub-link': 'https://citylab-berlin.org/de/projects/districtprofiles/',
  'Einsatzbereich': ['Innovative Verwaltung', 'Offene Daten, offene Städte']},
 'Algorithmische Stadtvisionen': {'sub-link': 'https://citylab-berlin.org/de/projects/stadtvisionen/',
  'Einsatzbereich': ['Neue Technologien']},
 'Berlin Urban Tech': {'sub-link': 'https://citylab-berlin.org/de/projects/startupmapping/',
  'Einsatzbereich': ['Offene Daten, offene Städte']},
 'Prototype Your Future City!': {'sub-link': 'https://citylab-berlin.org/de/projects/prototype/',
  'Einsatzbereich': ['Smart Cities für alle']}}

# Code for further pipeline

## Scrape regular data

In [5]:
%load_ext autoreload
%autoreload 2

from Webscraping.Citylab_Berlin.scrape_projects_from_citylab_website import scrape_citylab_berlin
from Webscraping.get_ai_data import enrich_projects_data_with_ai

# Scrape CityLAB Berlin Projects
citylab_berlin_projects = scrape_citylab_berlin(
		url="https://citylab-berlin.org/de/projects/",
		save_to_csv=False
	)

citylab_berlin_projects_enriched = enrich_projects_data_with_ai(citylab_berlin_projects)
citylab_berlin_projects_enriched

# TODO: CodeFor Scraping
# TODO: Civic Coding Scraping

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Successfully retrieved 40 projects from the CityLAB Berlin website.
Processing 40 rows...
[1/40] https://citylab-berlin.org/de/projects/baergpt/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'BärGPT', 'Art': 'KI-Anwendung, Chatbot, Dokumentenverwaltung', 'Einsatzbereich': 'Verwaltung, Öffentliche Verwaltung, Berliner Landesverwaltung'}
[2/40] https://citylab-berlin.org/de/projects/fairgnuegen/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Fairgnügen', 'Art': 'Analyse von Sensordaten und ML, Automatisierte Datenübermittlung, Beratung, Datenanalyse, Datenerhebung, Datenanwendung für Öffentlichkeit, Datenstandards, Datensatz und Visualisierung, Digitale Plattform, Entscheidungsassistent, Interaktive App, Interaktive Karte, Interaktiver Fragebogen, Interne Datenanwendung, KI Anwendung, Karte, Knowledge Graph, Large Language Model (LLM), Matching, Monitoring, Offene Daten, Output Monitoring, Plattform für Wahlentscheidungen, Prozessautomatisierung, Reporting, Skalierung der Wirkungsmessung, Sprach-Editor, Umfrage, Übersetzungsassistent, Vernetzungsassistent, Verzeichnis / Karte, Visualisierung mit Karten, Zugänglichkeit Offene Daten des Statistischen Bundesamts', 'Einsatzbereich': 'Armut, Barrierefreiheit, Beratung, Chancengleichheit, Demokratie, Gesundheit, Humanitäre Hilfe, Inklusion, Integration, International, Jugendbeteiligung, Jugendhilfe, Kinderschutz, Kältehilfe, Menschen mit Behinderung, Menschenrechte, Migration, Migrationsberatung, Nachhaltigkeit, Offene Daten, Partizipation, Patenschaft, Pflege, Queere Sichtbarkeit, Soziale Arbeit, Stadt, Stadtplanung, Teilhabe, Telemedizin, Transparenz, Umwelt, Umweltschutz, Vernetzung, Verwaltung, Wirkungsmessung, Wohlfahrt, Wohnen, Wohnungslosenhilfe'}
[3/40] https://citylab-berlin.org/de/projects/parla/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Parla', 'Art': 'KI Anwendung, Wissensmanagement, Verwaltungsdokumente', 'Einsatzbereich': 'Verwaltung, Politik, Informationsmanagement'}
[4/40] https://citylab-berlin.org/de/projects/kiezlabor/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Kiezlabor', 'Art': 'Partizipation, Stadtplanung, Smart City, Digitalisierung, Bürgerbeteiligung', 'Einsatzbereich': 'Berlin, Deutschland, Urban Development, Community Engagement'}
[5/40] https://citylab-berlin.org/de/projects/data-hub-berlin/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Data Hub Berlin', 'Art': 'Datenplattform, Open-Source, Datenmanagement, ETL-Prozesse, Visualisierung', 'Einsatzbereich': 'Verwaltung, Stadtentwicklung, Forschung'}
[6/40] https://citylab-berlin.org/de/projects/partizipation-digital/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'PaDi', 'Art': 'Digitale Plattform, Interaktive App, Interaktive Karte, Interaktiver Fragebogen, KI Anwendung, Large Language Model (LLM), Matching, Monitoring, Offene Daten, Output Monitoring, Plattform für Wahlentscheidungen, Prozessautomatisierung, Reporting, Skalierung der Wirkungsmessung, Sprach-Editor, Umfrage, Übersetzungsassistent, Vernetzungsassistent, Verzeichnis / Karte, Visualisierung mit Karten, Zugänglichkeit Offene Daten des Statistischen Bundesamts.', 'Einsatzbereich': 'Integration, Partizipation, Migration, Inklusion, Chancengleichheit, Gleichberechtigung, Gleichstellung, Gesundheit, Humanitäre Hilfe, Nachhaltigkeit, Offene Daten, Transparenz, Verwaltung, Wirkungsmessung, Wohlfahrt, Wohnen'}
[7/40] https://citylab-berlin.org/de/projects/govtech-testlab/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'GovTech TestLAB', 'Art': 'Testlabor, GovTech-Anwendungen, Verwaltungsdigitalisierung', 'Einsatzbereich': 'Berliner Verwaltung, Öffentliche Verwaltung, Digitalisierung'}
[8/40] https://citylab-berlin.org/de/projects/stadtlabor2go/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Stadtlabor2Go', 'Art': 'Analyse von Sensordaten und ML, Automatisierte Datenübermittlung, Bericht, Crowd-Sourced Daten, Dashboard, Datenanalyse, Datenerhebung, Datenanwendung für Öffentlichkeit, Datenstandards, Datensatz und Visualisierung, Digitale Plattform, Dokumentations- und Netzwerktool, Entscheidungsassistent, Festival und Studie, Generative KI, Interaktive App, Interaktive Karte, Interaktiver Fragebogen, Interne Datenanwendung, KI Anwendung, Karte, Knowledge Graph, Large Language Model (LLM), Matching, Monitoring, Offene Daten, Output Monitoring, Plattform für Wahlentscheidungen, Prozessautomatisierung, Reporting, Skalierung der Wirkungsmessung, Sprach-Editor, Umfrage, Übersetzungsassistent, Vernetzungsassistent, Verzeichnis / Karte, Visualisierung mit Karten, Zugänglichkeit Offene Daten des Statistischen Bundesamts.', 'Einsatzbereich': 'Stadtplanung, Digitalisierung, Bürgerbeteiligung, Verwaltung, Bildung, Forschung'}
[9/40] https://citylab-berlin.org/de/projects/giess-den-kiez/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Gieß den Kiez', 'Art': 'Interaktive Plattform, Open Data, Datenvisualisierung, Bürgerbeteiligung, Klimaschutz', 'Einsatzbereich': 'Umweltschutz, Stadtplanung, Bürgerengagement, Nachhaltigkeit'}
[10/40] https://citylab-berlin.org/de/projects/klimadashboard-xhain/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'KlimaDashboard Xhain', 'Art': 'Interaktive Visualisierung, Datenanalyse, Klimaschutz, Anpassung an den Klimawandel', 'Einsatzbereich': 'Klimaschutz, Stadtplanung, Bürgerbeteiligung, Transparenz'}
[11/40] https://citylab-berlin.org/de/projects/hilf-mir-berlin/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Hilf-Mir.Berlin', 'Art': 'Interaktive Karte, Beratung, psychosoziale Hilfe', 'Einsatzbereich': 'Gesundheit, mentale Gesundheit, Beratung'}
[12/40] https://citylab-berlin.org/de/projects/talking-treebot/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Interaktive App, KI Anwendung, Umweltsensor', 'Einsatzbereich': 'Bildung, Nachhaltigkeit, Umweltschutz'}
[13/40] https://citylab-berlin.org/de/projects/buergeramt-der-zukunft-tagebuchstudie/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Analyse von Sensordaten und ML, Automatisierte Datenübermittlung, Bericht, Datenanalyse, Datenerhebung, Datenanwendung für Öffentlichkeit, Datenstandards, Datensatz und Visualisierung, Digitale Plattform, Dokumentations- und Netzwerktool, Entscheidungsassistent, Interaktive App, Interaktive Karte, Interaktiver Fragebogen, Interne Datenanwendung, KI Anwendung, Karte, Knowledge Graph, Large Language Model (LLM), Matching, Monitoring, Offene Daten, Output Monitoring, Plattform für Wahlentscheidungen, Prozessautomatisierung, Reporting, Skalierung der Wirkungsmessung, Sprach-Editor, Umfrage, Übersetzungsassistent, Vernetzungsassistent, Verzeichnis / Karte, Visualisierung mit Karten, Zugänglichkeit Offene Daten des Statistischen Bundesamts', 'Einsatzbereich': 'Berlin, Antidiskriminierung, Antirassismus, Arbeit mit Kindern, Armut, Barrierefreiheit, Beratung, Chancengleichheit, Demokratie, Demenz, Datenschutz, Energie, Ethik, Evaluation, Frauen, Fundraising, Geflüchtete, Genderneutrale Sprache, Gleichberechtigung, Gleichstellung, Gesundheit, Humanitäre Hilfe, Indien, Inklusion, Integration, International, Jugendarbeit, Jugendbeteiligung, Jugendhilfe, Kamerun, Katastrophenschutz, Kältehilfe, Kinderschutz, Kinder- und Jugendhilfe, KI, Kongo, Kroatien, Landwirtschaft, Meeresschutz, Mentale Gesundheit, Mentoring, Menschen mit Behinderung, Menschenrechte, Migration, Migrationsberatung, Nachhaltigkeit, Offene Daten, Partizipation, Patenschaft, Pflege, Pflegende Angehörige, Queere Sichtbarkeit, Rettungsdienst, Senioren, Soziale Arbeit, Sport, Stadt, Stadtplanung, Teilhabe, Telemedizin, Transparenz, Türkei, Umwelt, Umweltschutz, Vernetzung, Verwaltung, Wirkungsmessung, Wohlfahrt, Wohnen, Wohnungslosenhilfe, Wissensmanagement'}
[14/40] https://citylab-berlin.org/de/projects/citylab-roadshow/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Verwaltungsinnovation, Digitalisierung, Service Design, Innovationsprojekte, Begleitung von Innovationsprojekten, Service Design für die Verwaltung, Nutzer:innenzentrierung, Methodenvermittlung, Wissensvermittlung, Teach the Trainer', 'Einsatzbereich': 'Berlin, Verwaltung, Öffentliche Verwaltung, Bezirksverwaltungen, Senatsverwaltungen'}
[15/40] https://citylab-berlin.org/de/projects/berliner-energiecheckpoint/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Berliner EnergieCheckpoint', 'Art': 'Interaktive Karte, Datenanalyse, Energie', 'Einsatzbereich': 'Energie, Klimaschutz, Nachhaltigkeit'}
[16/40] https://citylab-berlin.org/de/projects/smart_city/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'GD:B', 'Art': 'Smart City, Partizipation, Community Building, Workshop, Methodenbereitstellung, Leitfäden, Wissensmanagement, Evaluation', 'Einsatzbereich': 'Smart City, Stadtentwicklung, Nachhaltigkeit, Gemeinwohlorientierung, Resilienz, Kooperation'}
[17/40] https://citylab-berlin.org/de/projects/ki-zum-anfassen-unsere-interaktiven-exponate/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Interaktive App, Interaktive Karte, Interaktiver Fragebogen, KI Anwendung, Large Language Model (LLM), Matching, Monitoring, Offene Daten, Output Monitoring, Plattform für Wahlentscheidungen, Prozessautomatisierung, Reporting, Skalierung der Wirkungsmessung, Sprach-Editor, Umfrage, Übersetzungsassistent, Vernetzungsassistent, Verzeichnis / Karte, Visualisierung mit Karten, Zugänglichkeit Offene Daten des Statistischen Bundesamts.', 'Einsatzbereich': 'Beratung, Chancengleichheit, Demokratie, Evaluation, Frauen, Geflüchtete, Gleichberechtigung, Gleichstellung, Gesundheit, Humanitäre Hilfe, Inklusion, Integration, International, Jugendarbeit, Jugendbeteiligung, Jugendhilfe, KI, Partizipation, Patenschaft, Pflege, Queere Sichtbarkeit, Soziale Arbeit, Stadt, Stadtplanung, Teilhabe, Telemedizin, Transparenz, Vernetzung, Verwaltung, Wirkungsmessung, Wohlfahrt, Wohnen, Wohnungslosenhilfe.'}
[18/40] https://citylab-berlin.org/de/projects/labcamp/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Vernetzungstreffen öffentlicher Innovationslabore, Community of practice, Partizipationsansätze, Digitalisierungsprozesse', 'Einsatzbereich': 'öffentlicher Sektor, Zivilgesellschaft, Wissenschaft, Wirtschaft, Deutschland, Österreich, Schweiz'}
[19/40] https://citylab-berlin.org/de/projects/summerschool/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Interaktive App, Interaktive Karte, Interaktiver Fragebogen, Offene Daten, Prototyping, Skalierung der Wirkungsmessung, Stadtplanung, Teilhabe, Vernetzung, Visualisierung mit Karten', 'Einsatzbereich': 'Beratung, Chancengleichheit, Demokratie, Evaluation, Frauen, Geflüchtete, Gleichberechtigung, Gleichstellung, Gesundheit, Humanitäre Hilfe, Inklusion, Integration, Jugendbeteiligung, Jugendhilfe, Kinder- und Jugendhilfe, Partizipation, Soziale Arbeit, Stadtplanung, Teilhabe, Transparenz, Umwelt, Umweltschutz, Vernetzung, Verwaltung, Wirkungsmessung'}
[20/40] https://citylab-berlin.org/de/projects/berliner-weihnachtsmarkt-finder/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Interaktive Karte, Datenanalyse, Datenerhebung, Open Data', 'Einsatzbereich': 'Tourismus, Freizeit, Weihnachtsmärkte'}
[21/40] https://citylab-berlin.org/de/projects/digitalwerkstatt/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Datenanwendung für Öffentlichkeit, Digitale Plattform, Interaktive App, Prozessautomatisierung, Reporting, Umfrage, Vernetzungsassistent', 'Einsatzbereich': 'Verwaltung, Partizipation, Inklusion, Digitale Gesellschaft'}
[22/40] https://citylab-berlin.org/de/projects/werkstatt-im-citylab/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Experimente mit Methoden aus der Elektrotechnik und Informatik, Coding, Hardware', 'Einsatzbereich': 'Bildung, Empowerment, Partizipation, Inklusion'}
[23/40] https://citylab-berlin.org/de/projects/hacking-box-goes-citylab/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Hardwareboxen für Schulprojekte, Workshops, Seminare, Hackathons & Co., Digitale Plattform, Datenanwendung für Öffentlichkeit', 'Einsatzbereich': 'Schulprojekte, Workshops, Seminare, Hackathons, Bildung, Digitale Bildung, Lernangebot'}
[24/40] https://citylab-berlin.org/de/projects/digitalvereint/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Digital Vereint', 'Art': 'Plattform, Digitale Plattform, Interaktive App, Interaktive Karte, Interaktiver Fragebogen, Verzeichnis / Karte, Wissensmanagement, Offene Daten', 'Einsatzbereich': 'Ehrenamt, Engagement, Zivilgesellschaft, Digitalisierung, Bildung, Beratung, Partizipation, Inklusion, Transparenz'}
[25/40] https://citylab-berlin.org/de/projects/qtrees/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Qtrees', 'Art': 'Analyse von Sensordaten und ML, KI Anwendung, Predictive Analytics', 'Einsatzbereich': 'Umweltschutz, Stadtplanung, Klimawandel'}
[26/40] https://citylab-berlin.org/de/projects/afs-dashboard/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'AFS', 'Art': 'Dashboard, Datenanalyse, Verwaltungssteuerung', 'Einsatzbereich': 'Verwaltung, Statistik, Bürgerdienste'}
[27/40] https://citylab-berlin.org/de/projects/stadtpuls/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Datenanalyse, Datenerhebung, Datenanwendung für Öffentlichkeit, IoT-Datenplattform, Sensordaten', 'Einsatzbereich': 'Zivilgesellschaft, Citizen Science, Datenjournalismus, Bildung, Umwelt'}
[28/40] https://citylab-berlin.org/de/projects/pixelwelt/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Pixelwelt', 'Art': 'Interaktive App, Virtuelle Veranstaltungen, 2D-Modell, Digitale Plattform', 'Einsatzbereich': 'Veranstaltungen, Community, Ausstellung, Interaktion'}
[29/40] https://citylab-berlin.org/de/projects/prototypenwerkstatt/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Datenanalyse, Datenerhebung, Datenanwendung für Öffentlichkeit, Digitale Plattform, Dokumentations- und Netzwerktool, Entscheidungsassistent, Interaktive App, Interaktive Karte, Interaktiver Fragebogen, KI Anwendung, Knowledge Graph, Large Language Model (LLM), Matching, Monitoring, Offene Daten, Output Monitoring, Plattform für Wahlentscheidungen, Prozessautomatisierung, Reporting, Skalierung der Wirkungsmessung, Sprach-Editor, Umfrage, Übersetzungsassistent, Vernetzungsassistent, Verzeichnis / Karte, Visualisierung mit Karten, Zugänglichkeit Offene Daten des Statistischen Bundesamts.', 'Einsatzbereich': 'Arbeit mit Kindern, Armut, Barrierefreiheit, Beratung, Chancengleichheit, Demokratie, Demenz, Datenschutz, Energie, Ethik, Evaluation, Frauen, Fundraising, Geflüchtete, Genderneutrale Sprache, Gleichberechtigung, Gleichstellung, Gesundheit, Humanitäre Hilfe, Indien, Inklusion, Integration, International, Jugendarbeit, Jugendbeteiligung, Jugendhilfe, Kamerun, Katastrophenschutz, Kältehilfe, Kinderschutz, Kinder- und Jugendhilfe, KI, Kongo, Kroatien, Landwirtschaft, Meeresschutz, Mentale Gesundheit, Mentoring, Menschen mit Behinderung, Menschenrechte, Migration, Migrationsberatung, Nachhaltigkeit, Offene Daten, Partizipation, Patenschaft, Pflege, Pflegende Angehörige, Queere Sichtbarkeit, Rettungsdienst, Senioren, Soziale Arbeit, Sport, Stadt, Stadtplanung, Teilhabe, Telemedizin, Transparenz, Türkei, Umwelt, Umweltschutz, Vernetzung, Verwaltung, Wirkungsmessung, Wohlfahrt, Wohnen, Wohnungslosenhilfe, Wissensmanagement.'}
[30/40] https://citylab-berlin.org/de/projects/prozessanalyse-radinfrastruktur-pari/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'PARI', 'Art': 'Analyse von Prozessen und Verfahren', 'Einsatzbereich': 'Verkehr, Radinfrastruktur, Verwaltung'}
[31/40] https://citylab-berlin.org/de/projects/digitale-tools-fuer-radwegeplanung/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'FixMyBerlin', 'Art': 'Digitale Tools für Radwegeplanung, Radverkehrsplanung, Partizipation', 'Einsatzbereich': 'Verkehr, Mobilität, Radverkehr, Bürgerbeteiligung'}
[32/40] https://citylab-berlin.org/de/projects/schatten/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Datenvisualisierung, Offene Daten, Interaktive Karte', 'Einsatzbereich': 'Umwelt, Klimawandel, Stadtplanung'}
[33/40] https://citylab-berlin.org/de/projects/clair/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Clair Berlin', 'Art': 'Luftqualitätsmessung, Open Source, Datenplattform, Sensorik', 'Einsatzbereich': 'Öffentliche Räume, Schulen, Theater, Bibliotheken, Gesundheitswesen'}
[34/40] https://citylab-berlin.org/de/projects/aiforberlin/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'AI for Berlin', 'Art': 'KI-Anwendung, Workshopreihe', 'Einsatzbereich': 'Urbaner Raum, Nachhaltigkeit, Innovation'}
[35/40] https://citylab-berlin.org/de/projects/bikesharing/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Analyse von Sensordaten und ML, Datenanalyse, Datenerhebung, Datenanwendung für Öffentlichkeit, Datenstandards, Datensatz und Visualisierung, Digitale Plattform, Entscheidungsassistent, Interaktive App, Interaktive Karte, Interaktiver Fragebogen, Interne Datenanwendung, KI Anwendung, Karte, Knowledge Graph, Large Language Model (LLM), Monitoring, Offene Daten, Output Monitoring, Plattform für Wahlentscheidungen, Prozessautomatisierung, Reporting, Skalierung der Wirkungsmessung, Visualisierung mit Karten', 'Einsatzbereich': 'Berlin, Mobilitäts-Sharing-Anbieter, Leihfahrräder, E-Scooter, Stadtplanung, Verkehrsplanung'}
[36/40] https://citylab-berlin.org/de/projects/trafficcount/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': 'Open Traffic Count', 'Art': 'Verkehrszählung, Evaluierung, Open Source, Machine Learning', 'Einsatzbereich': 'Verkehr, Stadtplanung, Datenschutz'}
[37/40] https://citylab-berlin.org/de/projects/districtprofiles/
  -> Attempt 1: Using model meta-llama/llama-4-scout-17b-16e-instruct
AI result: {'Projekt-Abkürzung': '', 'Art': 'Interaktive Karte, Datenanalyse, Offene Daten', 'Einsatzbereich': 'Stadtplanung, Teilhabe, Transparenz'}
[38/40] https://citylab-berlin.org/de/projects/stadtvisionen/

    Index  ...                                                Art
0       0  ...        KI-Anwendung, Chatbot, Dokumentenverwaltung
1       1  ...  Analyse von Sensordaten und ML, Automatisierte...
2       2  ...  KI Anwendung, Wissensmanagement, Verwaltungsdo...
3       3  ...  Partizipation, Stadtplanung, Smart City, Digit...
4       4  ...  Datenplattform, Open-Source, Datenmanagement, ...
5       5  ...  Digitale Plattform, Interaktive App, Interakti...
6       6  ...  Testlabor, GovTech-Anwendungen, Verwaltungsdig...
7       7  ...  Analyse von Sensordaten und ML, Automatisierte...
8       8  ...  Interaktive Plattform, Open Data, Datenvisuali...
9       9  ...  Interaktive Visualisierung, Datenanalyse, Klim...
10     10  ...   Interaktive Karte, Beratung, psychosoziale Hilfe
11     11  ...        Interaktive App, KI Anwendung, Umweltsensor
12     12  ...  Analyse von Sensordaten und ML, Automatisierte...
13     13  ...  Verwaltungsinnovation, Digitalisierung, Servic...
14     14  ...           Interaktive Karte, Datenanalyse, Energie
15     15  ...  Smart City, Partizipation, Community Building,...
16     16  ...  Interaktive App, Interaktive Karte, Interaktiv...
17     17  ...  Vernetzungstreffen öffentlicher Innovationslab...
18     18  ...  Interaktive App, Interaktive Karte, Interaktiv...
19     19  ...  Interaktive Karte, Datenanalyse, Datenerhebung...
20     20  ...  Datenanwendung für Öffentlichkeit, Digitale Pl...
21     21  ...  Experimente mit Methoden aus der Elektrotechni...
22     22  ...  Hardwareboxen für Schulprojekte, Workshops, Se...
23     23  ...  Plattform, Digitale Plattform, Interaktive App...
24     24  ...  Analyse von Sensordaten und ML, KI Anwendung, ...
25     25  ...      Dashboard, Datenanalyse, Verwaltungssteuerung
26     26  ...  Datenanalyse, Datenerhebung, Datenanwendung fü...
27     27  ...  Interaktive App, Virtuelle Veranstaltungen, 2D...
28     28  ...  Datenanalyse, Datenerhebung, Datenanwendung fü...
29     29  ...                Analyse von Prozessen und Verfahren
30     30  ...  Digitale Tools für Radwegeplanung, Radverkehrs...
31     31  ...  Datenvisualisierung, Offene Daten, Interaktive...
32     32  ...  Luftqualitätsmessung, Open Source, Datenplattf...
33     33  ...                        KI-Anwendung, Workshopreihe
34     34  ...  Analyse von Sensordaten und ML, Datenanalyse, ...
35     35  ...  Verkehrszählung, Evaluierung, Open Source, Mac...
36     36  ...      Interaktive Karte, Datenanalyse, Offene Daten
37     37  ...            KI Anwendung, Stadtplanung, Architektur
38     38  ...      Datenbank, Vernetzung, Urban Tech, Smart City
39     39  ...  Analyse von Sensordaten und ML, Automatisierte...

[40 rows x 12 columns]

## Source Manual Data